server:
  port: 8082
spring:
  application:
    name: Kafka-Consumer-1
    bankName: Danske Bank
    bankId: 9%zM09LpUi%JjNmvjQEy
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
